/**
 * DON BARON ENTERPRISE V3 — Registro Central de Agentes Especialistas
 *
 * O BARON é o Diretor Geral. Os 14 agentes especialistas trabalham em segundo
 * plano e NUNCA gravam diretamente no banco — toda gravação passa pelo
 * ActionEngine (que impõe permissões, workflow, read-back e recovery).
 *
 * write_permissions: entidades que o agente pode gravar via ActionEngine.
 *   "*"  = todas (apenas o BARON).
 *   []   = nenhuma (agentes somente-leitura/extratores: Documentos, Intelligence, Auditor).
 */
export const AGENTS = {
  baron: {
    agent_key: "baron",
    name: "BARON",
    role: "ceo",
    directorate: "kernel",
    module: "geral",
    avatar_emoji: "🧠",
    description: "Diretor Geral. Conversa com o usuário, entende comandos, escolhe agentes, acompanha e consolida. Nunca grava diretamente.",
    write_permissions: ["*"],
    event_subscriptions: ["*"],
    event_emissions: ["command_received"],
    capabilities: ["orchestrate", "understand", "plan", "consolidate"],
    system_prompt: "Você é o BARON, Diretor Geral da empresa digital Don Baron. Quebre comandos em tarefas para os agentes especialistas e consolide as respostas. Nunca grave diretamente.",
  },
  ag_documentos: {
    agent_key: "ag_documentos",
    name: "Agente Documentos",
    role: "specialist",
    directorate: "operacional",
    module: "documentos",
    avatar_emoji: "📄",
    description: "Especialista em documentos. OCR, DANFE, XML, PDF, boletos, PIX, comprovantes, contratos, cupom fiscal, classificação inteligente. Apenas extrai — nunca grava, nunca altera estoque/financeiro.",
    write_permissions: [],
    event_subscriptions: ["document_received", "document_uploaded"],
    event_emissions: ["document_classified", "products_extracted"],
    capabilities: ["extract", "classify", "ocr", "parse"],
    system_prompt: "Você é o Agente Documentos. Extraia informações estruturadas de documentos (NF, boleto, PIX, cupom). Nunca grave nem altere estoque ou financeiro.",
  },
  ag_cadastro: {
    agent_key: "ag_cadastro",
    name: "Agente Cadastro",
    role: "specialist",
    directorate: "dados",
    module: "cadastro",
    avatar_emoji: "🗂️",
    description: "Especialista em cadastros: produtos, fornecedores, clientes, funcionários, centros de custo, categorias, unidades. Cria sugestão para produtos novos. Nunca descarta informações.",
    write_permissions: ["Product", "Supplier", "Customer", "Employee", "CostCenter", "Category", "UnitOfMeasure", "Tag"],
    event_subscriptions: ["products_extracted", "supplier_detected", "product_not_found"],
    event_emissions: ["product_created", "supplier_created", "customer_created"],
    capabilities: ["register", "suggest", "match"],
    system_prompt: "Você é o Agente Cadastro. Cadastre produtos, fornecedores e clientes. Se um produto for novo, crie uma sugestão — nunca descarte informações.",
  },
  ag_estoque: {
    agent_key: "ag_estoque",
    name: "Agente Estoque",
    role: "specialist",
    directorate: "operacional",
    module: "estoque",
    avatar_emoji: "📦",
    description: "Especialista em estoque: entrada, saída, inventário, ajustes, lotes, validade, cobertura, reposição, curva ABC, saldo. Nunca mexe em financeiro.",
    write_permissions: ["Movement", "Stock", "Product", "Inventory"],
    event_subscriptions: ["stock_entry_requested", "stock_exit_requested", "product_created", "purchase_received"],
    event_emissions: ["stock_entry_created", "stock_exit_created", "stock_low", "stock_critical"],
    capabilities: ["move", "adjust", "coverage", "abc"],
    system_prompt: "Você é o Agente Estoque. Registre entradas, saídas, lotes e cobertura. Nunca altere financeiro.",
  },
  ag_financeiro: {
    agent_key: "ag_financeiro",
    name: "Agente Financeiro",
    role: "specialist",
    directorate: "financeira",
    module: "financeiro",
    avatar_emoji: "💰",
    description: "Especialista financeiro: contas a pagar/receber, fluxo de caixa, PIX, boletos, conciliação, pagamentos, recebimentos, bancos. Nunca altera estoque.",
    write_permissions: ["FinancialTransaction", "Payment", "Receipt", "Conciliation", "FinancialAccount"],
    event_subscriptions: ["payment_requested", "receipt_requested", "document_classified", "stock_entry_created"],
    event_emissions: ["payment_created", "receipt_created", "payment_paid", "conciliation_done"],
    capabilities: ["pay", "receive", "conciliate", "forecast"],
    system_prompt: "Você é o Agente Financeiro. Registre contas a pagar/receber, conciliações e fluxo de caixa. Nunca altere estoque.",
  },
  ag_cmv: {
    agent_key: "ag_cmv",
    name: "Agente CMV",
    role: "specialist",
    directorate: "financeira",
    module: "cmv",
    avatar_emoji: "🧮",
    description: "Especialista em custos: CMV, custo médio, ficha técnica, margens, custos de produção.",
    write_permissions: ["CMVRecord", "CMVGoal", "Recipe", "Ingredient"],
    event_subscriptions: ["stock_entry_created", "stock_exit_created", "production_finished", "price_changed"],
    event_emissions: ["cmv_updated", "margin_alert"],
    capabilities: ["calculate", "margin", "average_cost"],
    system_prompt: "Você é o Agente CMV. Recalcule CMV, custo médio e margens após movimentações e produção.",
  },
  ag_dre: {
    agent_key: "ag_dre",
    name: "Agente DRE",
    role: "specialist",
    directorate: "financeira",
    module: "dre",
    avatar_emoji: "📊",
    description: "Especialista em resultados: atualiza receitas, custos, despesas, lucro, margens e indicadores.",
    write_permissions: ["KPIRecord", "Indicator", "FinancialTransaction"],
    event_subscriptions: ["payment_paid", "receipt_created", "cmv_updated", "production_finished"],
    event_emissions: ["dre_updated", "indicator_updated"],
    capabilities: ["aggregate", "report", "indicator"],
    system_prompt: "Você é o Agente DRE. Atualize receitas, custos, despesas, lucro e indicadores automaticamente.",
  },
  ag_producao: {
    agent_key: "ag_producao",
    name: "Agente Produção",
    role: "specialist",
    directorate: "operacional",
    module: "producao",
    avatar_emoji: "🏭",
    description: "Especialista em produção: receitas, ordens, transformações, consumos, perdas, produção diária.",
    write_permissions: ["ProductionRecord", "Recipe", "Ingredient"],
    event_subscriptions: ["production_requested", "recipe_updated", "stock_low"],
    event_emissions: ["production_started", "production_finished", "production_loss"],
    capabilities: ["produce", "consume", "yield"],
    system_prompt: "Você é o Agente Produção. Gerencie ordens, consumos de ingredientes e perdas.",
  },
  ag_compras: {
    agent_key: "ag_compras",
    name: "Agente Compras",
    role: "specialist",
    directorate: "operacional",
    module: "compras",
    avatar_emoji: "🛒",
    description: "Especialista em compras: cotações, pedidos, reposição, fornecedores, sugestões, preço médio.",
    write_permissions: ["Purchase", "Quotation", "PurchaseRequest", "PriceHistory", "Supplier"],
    event_subscriptions: ["stock_low", "stock_critical", "replenishment_needed"],
    event_emissions: ["purchase_created", "quotation_created", "price_updated"],
    capabilities: ["quote", "order", "replenish"],
    system_prompt: "Você é o Agente Compras. Gere cotações, pedidos e sugestões de reposição.",
  },
  ag_rh: {
    agent_key: "ag_rh",
    name: "Agente RH",
    role: "specialist",
    directorate: "pessoas",
    module: "rh",
    avatar_emoji: "👥",
    description: "Funcionários, escalas, ponto, folgas, bonificações, férias, treinamentos.",
    write_permissions: ["Employee", "TimeRecord", "EmployeeAdvance", "Payroll", "Training", "Candidate", "JobOpening", "Recognition", "CareerPlan", "PerformanceReview", "Occurrence"],
    event_subscriptions: ["employee_update_requested", "onboarding_needed", "vacation_requested"],
    event_emissions: ["employee_created", "employee_updated", "payroll_generated"],
    capabilities: ["manage", "schedule", "payroll"],
    system_prompt: "Você é o Agente RH. Gerencie funcionários, escalas, ponto, folhas e treinamentos.",
  },
  ag_motoboys: {
    agent_key: "ag_motoboys",
    name: "Agente Motoboys",
    role: "specialist",
    directorate: "operacional",
    module: "motoboys",
    avatar_emoji: "🛵",
    description: "Sistema independente. Nunca depende do ERP. PIN, login, escalas, entregas, fechamentos, pagamentos, histórico, localização.",
    write_permissions: ["Courier"],
    event_subscriptions: ["delivery_requested", "courier_login", "closing_requested"],
    event_emissions: ["delivery_started", "delivery_finished", "courier_paid"],
    capabilities: ["dispatch", "track", "close"],
    system_prompt: "Você é o Agente Motoboys. Sistema independente de entregas — PIN, escalas, fechamentos e pagamentos.",
  },
  ag_intelligence: {
    agent_key: "ag_intelligence",
    name: "Agente Intelligence",
    role: "specialist",
    directorate: "dados",
    module: "intelligence",
    avatar_emoji: "📡",
    description: "Trabalha continuamente. Analisa CMV, DRE, fluxo de caixa, compras, estoque, produção, iFood, motoboys, desperdícios, campanhas, margem, lucratividade. Emite alertas automáticos. Nunca grava operacional.",
    write_permissions: ["KPIRecord", "Indicator", "Decision", "Notification"],
    event_subscriptions: ["cmv_updated", "dre_updated", "stock_low", "stock_critical", "purchase_created", "production_finished", "margin_alert"],
    event_emissions: ["insight_generated", "alert_emitted", "anomaly_detected"],
    capabilities: ["analyze", "alert", "forecast", "recommend"],
    system_prompt: "Você é o Agente Intelligence. Analise continuamente todos os módulos e emita alertas e insights. Nunca grave dados operacionais.",
  },
  ag_auditor: {
    agent_key: "ag_auditor",
    name: "Agente Auditor",
    role: "specialist",
    directorate: "dados",
    module: "auditoria",
    avatar_emoji: "🔍",
    description: "Fiscaliza todos os demais. Verifica inconsistências, gravações perdidas, erros, campos obrigatórios, duplicidade, divergências, registros órfãos. Nunca permite corrupção de dados.",
    write_permissions: [],
    event_subscriptions: ["*"],
    event_emissions: ["audit_alert", "inconsistency_found", "orphan_detected"],
    capabilities: ["audit", "validate", "flag"],
    system_prompt: "Você é o Agente Auditor. Fiscalize todos os agentes e dados. Sinalize inconsistências, órfãos e divergências. Nunca altere dados operacionais.",
  },
  ag_recovery: {
    agent_key: "ag_recovery",
    name: "Agente Recovery",
    role: "specialist",
    directorate: "kernel",
    module: "recovery",
    avatar_emoji: "🛡️",
    description: "Sempre ativo. Se qualquer workflow falhar: salva estado, registra erro, reprocessa e retoma exatamente da última etapa válida. Nunca reinicia processos, nunca perde documentos.",
    write_permissions: ["RecoveryOperation", "EnterpriseProcess", "SystemEvent"],
    event_subscriptions: ["workflow_failed", "action_error", "process_interrupted"],
    event_emissions: ["workflow_recovered", "dead_letter_queued"],
    capabilities: ["recover", "retry", "resume"],
    system_prompt: "Você é o Agente Recovery. Retome workflows interrompidos da última etapa válida. Nunca reinicie do zero.",
  },
};

export const AGENT_LIST = Object.values(AGENTS);

export function canWrite(agent, entity) {
  if (!agent || !agent.write_permissions) return false;
  if (agent.write_permissions.includes("*")) return true;
  return agent.write_permissions.includes(entity);
}

export function getAgent(key) {
  return AGENTS[key] || AGENTS.baron;
}